name: CI

on:
  push:
    branches:
      - main

jobs:
  transpire-ci:
    uses: ocf/transpire-ci/.github/workflows/trigger.yml@master
    with:
      module_name: labmap2
    secrets:
      TRANSPIRE_CI_PAT: ${{ secrets.TRANSPIRE_CI_PAT }}
